version: '3.7'
services:
  nestjs-todo-backend:
    container_name: nestjs-todo-backend
    build:
      context: .
      # target: development
    depends_on:
      - postgres-db
    env_file: .env
    environment:
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    volumes:
      - .:/opt/app/nestjs-todo-backend

  postgres-db:
    container_name: postgres-db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    image: postgres:11-alpine
    ports:
      - 5432:5432
