version: '3.7'
services:
  nestjs-todo-backend:
    container_name: nestjs-todo-backend
    build:
      context: .
      target: development
      cache_from:
        - node:12.16.1-alpine
    depends_on:
      - postgres-db
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    volumes:
      - .:/opt/app/nestjs-backend
      - .:/opt/app/nestjs-backend/node_modules
    networks:
      - webnet
    command: yarn start:dev

  postgres-db:
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata:
