version: '3.7'
services:
  nestjs-todo-backend:
    build:
      context: .
      cache_from:
        - node:12.16.1-alpine
    container_name: nestjs-todo-backend
    depends_on:
      - nestjs-todo-db
    environment:
      - DB_URL=postgres://root:password@nestjs-todo-db/nestjs-db?charset=UTF8
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/app/nestjs-backend

  nestjs-todo-db:
    container_name: nestjs-todo-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nestjs-db
    image: postgres:11-alpine
    ports:
      - 0.0.0.0:7200:5432
